### ISSUE TITLE
Issue when using with Bitindi Chain 

### ISSUE THREAD

**Issue by kumarbitindi** [thirdweb-example/marketplace-v3#1]
import { CHAIN_ID_TO_NAME, NFT, ThirdwebSDK } from "@thirdweb-dev/sdk";  **('"@thirdweb-dev/sdk"' has no exported member named 'CHAIN_ID_TO_NAME'. Did you mean 'ChainIdOrName'?)**

 "isApprovedForAll",
      nft.owner, **(Argument of type 'string' is not assignable to parameter of type 'any[]'.ts(2345))**
      MARKETPLACE_ADDRESS
    );

    // If it is, provide approval
    if (!hasApproval) {
      const txResult = await nftCollection?.call(
        "setApprovalForAll",
        MARKETPLACE_ADDRESS,  **Argument of type 'string' is not assignable to parameter of type 'any[]'.ts(2345)**
        true
      );

**Comment by wabi88** [comment]
I'm also receiving this error

**Comment by saminacodes** [comment]
Hey friends! We recently updated this template to the latest version of our SDK which hopefully resolves this issue. If you are still having any issues with the template please let us know!
