### ISSUE TITLE
Build code failed

### ISSUE THREAD

**Issue by leecho** [thirdweb-example/marketplace-v3#20]
localhost colake-marketplace % yarn deploy
yarn run v1.22.19
$ next build && next export && npx thirdweb@latest upload out
   Linting and checking validity of types  ..Failed to compile.

./node_modules/abitype/dist/types/human-readable/formatAbi.d.ts:18:35
Type error: Type parameter declaration expected.

  16 |  * @returns Human-readable ABI
  17 |  */
> 18 | export declare function formatAbi<const TAbi extends Abi | readonly unknown[]>(abi: TAbi): FormatAbi<TAbi>;
     |                                   ^
  19 | //# sourceMappingURL=formatAbi.d.ts.map
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

localhost colake-marketplace % node -v
v18.18.2

**Comment by saminacodes** [comment]
Hey there! We recently updated this template to address a lot of issues- could you try it again and let us know if you run into issues?
