### ISSUE TITLE
BSC Not Support

### ISSUE THREAD

**Issue by SoraKohaku** [thirdweb-example/marketplace-v3#23]
Hello i now today using this thirdweb. since it's good using. and i build contract here too.. but the problem after add NFT i need using bnb network and this one sepolia. the bug happened after changes the code to BSC

From

```
import { sepolia } from "thirdweb/chains";
export const NETWORK = sepolia;
```

To

```
import { bsc } from "thirdweb/chains";
export const NETWORK = bsc;
```

Got error id thing. did anything i need fixed?

**Comment by saminacodes** [comment]
Can you post the full error message please? Will look into it

**Comment by SoraKohaku** [comment]
![codes](https://github.com/thirdweb-example/marketplace-v3/assets/11433397/a35b7af9-dafd-4cee-9d29-29c43899a8b6)
![error](https://github.com/thirdweb-example/marketplace-v3/assets/11433397/a4157ff8-2f57-4174-90f3-fa16d3202c81)

**Comment by saminacodes** [comment]
Looks like bsc was not a supported default chain in the chains package- in cases like these you can use defineChain https://portal.thirdweb.com/references/typescript/v5/defineChain

But, we also just added it as a default chain yesterday to make it easier for you - see PR: https://github.com/thirdweb-dev/js/pull/3024

Hope this helps! Let us know.

**Comment by SoraKohaku** [comment]
ok thanks. atm you guys need update npm thing it's still not added. need put manual Update. the thirdweb is simple than another site with many bugs. hope you guys do swap engine and anything cause. it's less memory using.

![image](https://github.com/thirdweb-example/marketplace-v3/assets/11433397/9b854ac4-a95b-478a-85b5-5febce70123f)
