### ISSUE TITLE
NFT721 Drop Contracts is not showing in Sell page

### ISSUE THREAD

**Issue by ryjin111** [thirdweb-example/marketplace-v3#25]
It seems it's not fetching anything or not detecting any collection within it's page

I've tried changing getNFTs and works but it's not showing the metadata and stuffs

**Comment by kien-ngo** [comment]
Hi there, the Sell page is using an extension (tokensOfOwner) that might not be available in your contract. Can you share the contract + chain with me so I can double check?

Also, is `getNFTs` throwing you any issue?

**Comment by ryjin111** [comment]
![image](https://github.com/thirdweb-example/marketplace-v3/assets/81433235/25b7fcc3-696e-4389-904f-36ebc26f1e38)
0x2Fb2aE31b5C48D0Fd327a460671FA131a6738068 NFT721 drop
Degen Chain
0x66bd7DBeFF2cC008Af80a8CBcAe1C6EC3086B5b1 MP

**Comment by kien-ngo** [comment]
Hey @ryjin111 sorry about the delay here. Are you using `getNFTs` which results in the error above? If you can share your full code here I believe I can give you a solution.

If you feel comfortable for a more private conversation, feel free to reach out to us at https://thirdweb.com/support

**Comment by ryjin111** [comment]
The code is just the new marketplace v3 repo which i fork @kien-ngo 

Tried everything i think thirdweb need to release a simple fix for this so that nftdrop721 contracts can use it perfectly on the selling page 

Other functions works well like direct buy

**Comment by kemiani** [comment]
> Otras funciones funcionan bien como la compra directa.

I just cloned the repository and configured the chain, but on the default purchase page it does not seem to show the nfts correctly, and the purchase or offer does not work within the nft information either.

**Comment by kien-ngo** [comment]
Hey guys, we are launching a new marketplace and although the UI isn't "the best", it's packed with features. Would you be able to play with it and give the suggestions + any bugs that you may find?

Live: https://marketplace-template.thirdweb-example.com/
Code base: https://github.com/thirdweb-example/marketplace-template

**Comment by Goutamdhanani** [comment]
i got similar issue. in sell page NFTS not loading.
i am using same contract marketplacev3 and direct listing contract . please help in this project only 
![Screenshot 2024-06-12 220831](https://github.com/thirdweb-example/marketplace-v3/assets/106019412/ba99c4b3-43c2-4d6e-9cf5-f3a56a92d5b8)

**Comment by ryjin111** [comment]
> i got similar issue. in sell page NFTS not loading. i am using same contract marketplacev3 and direct listing contract . please help in this project only ![Screenshot 2024-06-12 220831](https://private-user-images.githubusercontent.com/106019412/339219782-ba99c4b3-43c2-4d6e-9cf5-f3a56a92d5b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzExNjIsIm5iZiI6MTcxODM3MDg2MiwicGF0aCI6Ii8xMDYwMTk0MTIvMzM5MjE5NzgyLWJhOTljNGIzLTQzYzItNGQ2ZS05Y2Y1LWYzYTU2YTkyZDViOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzE0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjhhZGZjMDFkNjlhMDUxNzA2NGExNzJiZWM2ZGU4N2Q4NTFlMWQ5MmUyNTc0MDZhNzE3MjExMTEyYzEzN2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l5xe0l-eprGgI-3CbiD9NadqhNqUWirU7UyKvc0b3cM)

try the new template
Code base: https://github.com/thirdweb-example/marketplace-template
