### ISSUE TITLE
Error after attempting to load assets from the "Buy" page of imported contract. Error serializing '.contractMetadata.description'

### ISSUE THREAD

**Issue by Jharmony** [thirdweb-example/marketplace-v3#4]
After following your details instruction, which includes deploying my marketplacev3 contract and importing my ERC-721A collection on the Thirdweb dashboard, I continue to get an error on the "buy" component of the dapp. The NFTs from my collection do load successfully on the grid, but when I attempt to load anyone NFT to see further details this error shows up:
`Server Error
Error: Error serializing `.contractMetadata.description` returned from `getStaticProps` in "/token/[contractAddress]/[tokenId]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.`

I've also submitted a similar issue when attempting to load the marketplace contract and imported collection contract on the help section of the official discord which could be found here:

![image](https://github.com/thirdweb-example/marketplace-v3/assets/22645740/f2ec98db-eeb9-4a63-bce5-10176d0cdcdd)

**Comment by timmaycastags** [comment]
Hey Jharmony.  I had the same problem.  I was able to fix it by adding a JSON.stringify() while getting the metadata from the contract.  I updated the line in the [tokenId].tsx file.
line 371
`    contractMetadata = await JSON.stringify(contract.metadata.get());`

Hope that helps.

**Comment by saminacodes** [comment]
Hey friends! We recently updated this template to the latest version of our SDK which hopefully resolves this issue. If you are still having any issues with the template please let us know!
